on:
  push:
    branches:
      - main
name: Deploy website to live environment on main push
jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    steps:
      - name: Fire backup code
        run: |
          curl --request GET \
          --header 'X-OTAP-KEY: ${{ secrets.OTAP_KEY }}' \
          --url http://webfs.avametix.xyz/api/backup
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.avametix.xyz
          username: production@webfs.avametix.xyz
          password: ${{ secrets.FTP_PASS_PROD }}
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Fire install code
        run: |
          curl --request GET \
          --header 'X-OTAP-KEY: ${{ secrets.OTAP_KEY }}' \
          --url http://webfs.avametix.xyz/api/install
